---
abstract: 'Some Perl::Critic::Policies to search for needed refactoring'
author:
  - 'Markus Demml <mardem@cpan.com>'
build_requires:
  Cwd: '0'
  English: '0'
  Path::This: '0'
  Pod::Coverage: '0'
  Test2::Tools::Exception: '0'
  Test2::V0: '0'
  Test::CheckManifest: '0'
  Test::More: '0'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
configure_requires:
  Module::Build: '0.4004'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-Mardem
provides:
  Perl::Critic::Mardem:
    file: lib/Perl/Critic/Mardem.pm
    version: '0.05'
  Perl::Critic::Mardem::Util:
    file: lib/Perl/Critic/Mardem/Util.pm
    version: '0.05'
  Perl::Critic::Policy::Mardem::ProhibitBlockComplexity:
    file: lib/Perl/Critic/Policy/Mardem/ProhibitBlockComplexity.pm
    version: '0.05'
  Perl::Critic::Policy::Mardem::ProhibitConditionComplexity:
    file: lib/Perl/Critic/Policy/Mardem/ProhibitConditionComplexity.pm
    version: '0.05'
  Perl::Critic::Policy::Mardem::ProhibitFileSize:
    file: lib/Perl/Critic/Policy/Mardem/ProhibitFileSize.pm
    version: '0.05'
  Perl::Critic::Policy::Mardem::ProhibitLargeBlock:
    file: lib/Perl/Critic/Policy/Mardem/ProhibitLargeBlock.pm
    version: '0.05'
  Perl::Critic::Policy::Mardem::ProhibitLargeFile:
    file: lib/Perl/Critic/Policy/Mardem/ProhibitLargeFile.pm
    version: '0.05'
  Perl::Critic::Policy::Mardem::ProhibitLargeSub:
    file: lib/Perl/Critic/Policy/Mardem/ProhibitLargeSub.pm
    version: '0.05'
  Perl::Critic::Policy::Mardem::ProhibitManyConditionsInSub:
    file: lib/Perl/Critic/Policy/Mardem/ProhibitManyConditionsInSub.pm
    version: '0.05'
  Perl::Critic::Policy::Mardem::ProhibitReturnBooleanAsInt:
    file: lib/Perl/Critic/Policy/Mardem/ProhibitReturnBooleanAsInt.pm
    version: '0.05'
requires:
  Exporter: '0'
  List::Util: '0'
  Perl::Critic: '0'
  Perl::Critic::Policy: '0'
  Perl::Critic::Utils: '0'
  Perl::Critic::Utils::McCabe: '0'
  Readonly: '0'
  perl: '5.01'
resources:
  bugtracker: https://github.com/mardem1/perl-critic-mardem/issues
  homepage: https://github.com/mardem1/perl-critic-mardem
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mardem1/perl-critic-mardem.git
version: '0.05'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
